server:
  port: 8082
  servlet:
    context-path: /boot

name: 张三-dev
age: 18

person:
  name: 李四-dev
  age: 23
content: "cupSize:${person.name}, age:${age}"
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver